### ISSUE TITLE
backlog

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/lab-markdown#26]
# Backlog 

## Travail à faire

- Création de la liste des tâches
- Validation avec le formateur
- Création des issues
- Changement les noms des fichier dans le dossier backlog :
    - Ordre.Titre_issue.Numero_issue.md
- Les issues sont enregistrer dans des sous-dossiers qui représente des labels des issues

## Livrable

- backlog/*

**Comment by husseinbouik** [comment]
- Il faut respecter l'ordre des tâches 
    - la tache a realiser : init-rapport

**Comment by essarraj-fouad** [comment]
Il existe plusieurs pullrequest ouvert pour l'issue
