### ISSUE TITLE
installation-extentions

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/lab-markdown#27]
# Installation des extentions

## Travail à faire
- Installation 
  - Name: Markdown All in One
  - Id: yzhang.markdown-all-in-one
- Live coding des features
  - https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one

## Livrable

- docs/installation-extentions/images/*
- docs/installation-extentions/images/installation-extentions.pptx
- docs/installation-extentions/installation-extentions.md

**Comment by husseinbouik** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue

**Comment by husseinbouik** [comment]
- le pullrequest a un coflit
